config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: 'toppage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :toppage, only: :index
  resources :posts
  resources :users, only: [:show,:edit,:update]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :place
  belongs_to :style
  has_many :post_questions, dependent: :destroy
  has_many :questions, through: :post_questions

  paginates_per 5

  #質問のカウントを1増やす仕組み
  def counter
    self.questions.each do |question|
      counter = question.counter.to_i
      counter += 1
      question.update(counter: counter)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show,:edit,:update,:destroy]
  #登校一覧
  def index
    @posts = Post.order("id DESC").page(params[:page])
  end
  #新規投稿
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      #チェックされた質問のカウントを一つ増やす
      @post.counter
      redirect_to root_path
    else
      render :new
    end
  end
#投稿詳細
  def show
    @style = Style.find(@post.style_id)
    @place = Place.find(@post.place_id)
  end
#投稿編集
  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to  post_path(@post), notice:"投稿内容を編集しました！"
    else
      render :edit
    end
  end
#投稿削除
  def destroy
    @post.destroy
    flash[:success] = '投稿を削除しました！'
    redirect_to root_path
  end

  private
  
  def post_params
    params.require(:post).permit(
      :interview_date,
      :text,
      :user_id,
      :place_id,
      :style_id,
      question_ids: []).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/views/posts/_form.html.haml
.main_postcontent_form
  = form_with model:@post, local: true do |f|
    .field
      = f.label :業務形態, class: "field_name"
      = f.collection_select :style_id, Style.all, :id, :business_form, :include_blank => true
    .field
      = f.label :勤務地域, class: "field_name"
      = f.collection_select :place_id, Place.all, :id, :work_location, :include_blank => true 
    .field
      = f.label :面接日, class: "field_name"
      = f.date_field  :interview_date, class: "field_date"
    .field
      = f.label :質問内容, class: "field_name"
      .field_question
        = f.collection_check_boxes(:question_ids, Question.all, :id, :content, include_hidden: false) do |q|
          .field_question_answer
            = q.check_box
            = q.label{ q.text }
    .field
      = f.label :コメント, class: "field_name"
      .field_textarea
        = f.text_area :text
    .submit
      = f.submit

app/views/posts/edit.html.haml
%body
  %header
    = render 'share/header'
  .main
    .main_postcontent
      %h1 投稿詳細画面
      = render 'form'

app/views/posts/index.html.haml
%body
  %header
    = render 'share/header'
  .main
    .postindex
      %h1 投稿一覧
      .postindex_posts
        - @posts.each do |post|
          .post
            .post_user
              .post_user_image
                /あとで画像組み込み
                画像
              .post_user_name
                投稿者:
                = post.user.nickname
            .post_contents
              .post_contents_content
                .post_contents_content_info
                  .label
                    投稿日
                  .post_contents_content_info_text
                    = post.interview_date
                .post_contents_content_info
                  .label
                    業務形態
                  .post_contents_content_info_text
                    = post.style.business_form
                .post_contents_content_info
                  .label
                    勤務地域
                  .post_contents_content_info_text
                    = post.place.work_location
              .post_contents_questions
                .label
                  質問内容
                - post.questions.each do |question|
                  .question
                    = icon("far", "far fa-check-square")
                    = question.content
            .post_info
              = link_to "/posts/#{post.id}" do
                = icon("fas", "fas fa-arrow-circle-right")
                詳細を確認する
      .paginate
        = paginate @posts

app/views/posts/new.html.haml
%body
  %header
    = render 'share/header'
  .main
    .main_postcontent
      %h1 新規投稿
      = render 'form'

app/views/posts/show.html.haml
%body
  %header
    =  render 'share/header'
  .main
    .main_postcontent_show
      %h1 投稿詳細
      .main_postcontent_show_form
        .title
          .label
            %h2 面接日
            .label_text
              = @post.interview_date
          .label
            %h2 業務形態
            .label_text
              = @style.business_form
          .label
            %h2 勤務地域
            .label_text
              = @place.work_location
        .question
          %h2 質問内容
          - @post.questions.each do |quesion|
            .question_text
              = icon("far", "far fa-check-square")
              = quesion.content
        .comment
          %h2 コメント
          .comment_text
            = @post.text
        .actions
          = link_to "編集", edit_post_path
          = link_to "削除", post_path(@post.id), method: :delete, data: { confirm: '本当に削除していいですか？' }